{% set name = "types-ujson" %}
{% set version = "5.7.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-ujson-{{ version }}.tar.gz
  sha256: 638b3eff421903487e076670a3a31b79b7a5cb7a29eec50a6f0240cc3f7c4840

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/ujson-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for ujson
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
